import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import { StoreProvider } from "@/providers/store.provider";
import { Toaster } from "@/components/ui/sonner";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Buy From Egypt ",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <StoreProvider>{children}</StoreProvider>
        <Toaster richColors theme="light" position="top-left" closeButton duration={300000} />
      </body>
    </html>
  );
}
